# netlify.toml

[[redirects]]
  from = "/*"
  to = "/public/login.html"  # Ruta relativa a la carpeta login dentro de public
  status = 200

[build]
  command = "npm start"  # Cambia esto si es necesario
  publish = "public"  # Cambia esto si la carpeta de compilación es diferente
